apiVersion: v1
kind: ConfigMap
metadata:
  name: credential-config
  namespace: credential
  labels:
    app.kubernetes.io/name: credential-classification
    app.kubernetes.io/component: web
data:
  APP_BASE_URL: "http://127.0.0.1:8000"
  SSO_MODE: "mock"
  SSO_BROKER_EMPLOYEE_HEADER: "X-Broker-Employee-Id"
  SSO_BROKER_NAME_HEADER: ""
  SSO_BROKER_EMAIL_HEADER: ""
  SSO_BROKER_DEPT_HEADER: "deptname"
  BROKER_URL: "https://sso.example.com/svc0"
  SERVICE_URL: "https://example1.com"
  MAIL_MODE: "disabled"
  MAIL_API_BASE_URL: "mail.net"
  MAIL_API_TIMEOUT_SECONDS: "10"
