apiVersion: v1
kind: Secret
metadata:
  name: credential-secrets
  namespace: credential
  labels:
    app.kubernetes.io/name: credential-classification
    app.kubernetes.io/component: web
type: Opaque
stringData:
  DATABASE_URL: "mysql+pymysql://credential_user:change-me@mysql.internal:3306/credential?charset=utf8mb4"
  SSO_TOKEN_SECRET: "change-me-to-random-32-byte-secret"
  MAIL_API_BASE_URL: "mail.net"
  MAIL_API_SYSTEM_ID: "credential-system"
